apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: petclinic-openai-secret
  namespace: petclinic-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: petclinic-openai-secret
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: petclinic/dev/openai-api-key
        property: api-key
