apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: petclinic-dev
spec:
  provider:
    aws:
      service: SecretsManager
      region: af-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
